# Generated by Django 4.2.4 on 2023-09-28 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_rename_user_name_userlog_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_photo',
            new_name='avatar',
        ),
    ]
